### ISSUE TITLE
使用时提示libtinfo.so.5: no version information available，这个怎么解决？

### ISSUE THREAD

**Issue by gigglesun** [Snape3058/SPrinter#1]
错误信息如下：
`/home/qsun/bin/clang-tidy: /lib64/libtinfo.so.5: no version information available (required by /home/qsun/bin/clang-tidy)
/home/qsun/bin/clang-tidy: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/qsun/bin/clang-tidy)
/home/qsun/bin/clang-tidy: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/qsun/bin/clang-tidy)
`

**Comment by Snape3058** [comment]
You can use `ldd` command to detect what shared libraries are required and which ones are missing. Install these libraries manually.

On ubuntu, you can install the `libtinfo5` package.

BTW, if you do not mind, could you please tell me what are you using the tool for? And if you have any ideas about how to improve this tool, you can also share them with me. I'd very like to improve it.

**Comment by gigglesun** [comment]
@Snape3058 l checked with ldd and install it manually but it do not work, there are other libtinfo.so.5 in our system,it not work either. I would like to use this software to check the shared pointer NULL usage in our code, eg below code
 `
std::unique_ptr<int> ptr;
*ptr;
`
This software seems is the only software that can detect shared pointer NULL usage for now, appreciate for your great work! I would like to know if there is a better way to bypass this. Also, what is the license for it,same as clang-tidy? Can it open source and be part of the clang-tidy officially?

**Comment by Snape3058** [comment]
@gigglesun 
> l checked with ldd and install it manually but it do not work, there are other libtinfo.so.5 in our system,it not work either.

On the server where the tool was built, the `libtinfo.so.5` library is linked to `/lib/x86_64-linux-gnu/libtinfo.so.5` which is provided by the package `libtinfo5`. So, if it still cannot be correctly linked, maybe you can try docker?
Currently there are no docker images released, but if you really need it, I will try to create one ASAP during my spare time.

> I would like to use this software to check the shared pointer NULL usage in our code, ...

The tool is designed to prevent obvirous errors and detect the bad usages that are potentially bug prone. If you want to check the errors in the example, mayby the other tool based on Clang Static Analyzer (CSA), which is now under developing, will fit your requirements better (but it is not publicly available for now). The tool is based on coding style checking, which cannot track any data-flow information. In other words, this tool cannot detect such errors in your example.

> Also, what is the license for it,same as clang-tidy? Can it open source and be part of the clang-tidy officially?

It is not the problem of license. As a research tool it is, all the code is owned by my boss. I cannot public the source code without his permission. And currently, I am busy working on the CSA based tool now, I have no time working on this project before the new paper gets published. But all these things are on the schedule, maybe the next year.

If you (or your team) are interested in this tool or the new CSA based tool under developing and want to try it in your project, you can try to contact my boss. You can find the email address from the [tool demo paper](http://lcs.ios.ac.cn/~maxt/SPrinter/ASE-2019-Tool.pdf).

**Comment by gigglesun** [comment]
Solved this issue by using a LLVM with version 9.0.0. Replace the clang-tidy tool in it from clang-tidy from here can work well.
